export const FETCH_DESTINATIONS = 'FETCH_DESTINATIONS';
export const ADD_DESTINATION = 'ADD_DESTINATION';
export const FETCH_DESTINATION = 'FETCH_DESTINATION';
export const SEARCH_DESTINATIONS = 'SEARCH_DESTINATIONS';
